### ISSUE TITLE
Empty-ish "Code" section in the documentation

### ISSUE THREAD

**Issue by StanczakDominik** [joglekara/VlaPy#19]
I was looking through the [Code](https://vlapy.readthedocs.io/en/latest/code.html) section of the documentation and it seems empty. Looking at https://github.com/joglekara/VlaPy/blob/master/docs/code/fokker-planck.rst, I'm not yet sure why it doesn't include anything... https://github.com/joglekara/VlaPy/blob/master/vlapy/core/lenard_bernstein.py does have docstrings. Might be worth looking at the Sphinx build for any warnings it could be raising. I can try looking at it a bit later.

**Comment by StanczakDominik** [comment]
Ah, there you go, [I looked through the RTD build logs](https://readthedocs.org/api/v2/build/10909708.txt):

> WARNING: autodoc: failed to import module 'field' from module 'vlapy.core'; the following exception was raised:
> No module named 'numpy'
> WARNING: autodoc: failed to import module 'lenard_bernstein' from module 'vlapy.core'; the following exception was raised:
> No module named 'numpy'
> WARNING: autodoc: failed to import module 'manager' from module 'vlapy'; the following exception was raised:
> No module named 'mlflow'
> WARNING: autodoc: failed to import module 'storage' from module 'vlapy'; the following exception was raised:
> No module named 'xarray'
> WARNING: autodoc: failed to import module 'vlasov' from module 'vlapy.core'; the following exception was raised:
> No module named 'numpy'

Looks like we'll need to add a `.readthedocs.yml` file at the root of the repository to point RTD towards the requirements for the package. Here's an example: https://docs.readthedocs.io/en/stable/config-file/v2.html#python

**Comment by joglekara** [comment]
Thanks for sussing that out!

I've linked the PR here, too.
