### ISSUE TITLE
More responsive simulation running?

### ISSUE THREAD

**Issue by StanczakDominik** [joglekara/VlaPy#20]
`run_vlapy.py` could use some sort end-run notification on what to do next - there was no feedback that any simulation was being run, except a notification about a directory being created. A brief summary of https://vlapy.readthedocs.io/en/latest/#quick-usage could be nice - and I always recommend https://github.com/tqdm/tqdm for any simulation :smile:

**Comment by joglekara** [comment]
Thanks for the feedback. 

Looking forward to hearing what you think about the linked PR
