### ISSUE TITLE
Updates for the `Landau_damping` notebook

### ISSUE THREAD

**Issue by StanczakDominik** [joglekara/VlaPy#21]
The notebook needs a few updates:

- [ ] The "add `..` to sys.path"  trick at the start made my import fail. It would also fail with the notebook in any other location. I think if the setup.py install or pip install of the package goes through well, it should be unnecessary.
- [ ] The `from vlapy` import needs to be replaced with `from vlapy.core`.
   - [ ] To prevent this kind of issue, I think the notebook could be put into CI and rendered via nbsphinx through readthedocs; [I recently did that for PlasmaPy](https://github.com/PlasmaPy/PlasmaPy/pull/792) and could contribute that. There's also a way to build the docs for every PR; ~~it was somewhere along here https://github.com/orgs/readthedocs/projects/8 . I'll try to recall where the sign up for that is.~~ According to https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html you can sign up for it via email.
- [ ] The notebook - especially the "Initialize and run" part - could definitely use some more breaking up to explain the defined variables, especially the commented out sets of those. Drop some more narrative in!

* A question, because the docs weren't really clear on that - what's the connection between the notebook and the MLFlow style run? does the notebook implement the same sort of simulation?
* A stretch goal - I would have loved an animation to go along with the 2D plot ([`xarray.interactive`](https://github.com/pydata/xarray/issues/3709) may soon be an option to do that). That's completely optional, though.

**Comment by joglekara** [comment]
Thanks for the feedback here.

This notebook is quite a relic at this point. I made it early on in an effort to clarify the API but it's beyond needing a simple update or two, as you rightfully have pointed out.

I vote to remove it. What do you think?

**Comment by joglekara** [comment]
Here's a slightly more updated notebook but still needs to be brought up to full speed:
https://github.com/joglekara/VlaPy/tree/ld_notebook_mlflow/notebooks

Would be happy to have a contributor on it, though!

**Comment by StanczakDominik** [comment]
The other notebook you've linked is really lovely in terms of displaying the current API! I think taking the explanations from the first one and adding some explanations for each of the physics parameters makes this a great downloadable introduction.

I'll try to find something in the next few days to procrastinate away by adding nbsphinx to the docs :laughing:

**Comment by StanczakDominik** [comment]
Plasmapy's PR 792 is still stalled on review, but I think I could quickly add nbsphinx here, if you're down for that :smiley:

**Comment by joglekara** [comment]
@StanczakDominik let's do it!

**Comment by StanczakDominik** [comment]
I merged nbsphinx into plasmapy yesterday; now that I got a second opinion there that I'm not doing anything wildly unreasonable, I feel more comfortable adding it here. I'll get it done by tomorrow - likely today.

**Comment by StanczakDominik** [comment]
Hey, re: nbsphinx, I've been thinking about it a bit more and realized that the execute-notebook-at-doc-build part is not going to play nicely with MLFlow having to be launched before execution - its only use would be to include the already built notebook, but there's strong risk of the notebook diverging from the main API.

**Comment by joglekara** [comment]
ah, np. Regardless, thanks for looking into it @StanczakDominik !
