### ISSUE TITLE
More explicit variable  docstrings!

### ISSUE THREAD

**Issue by StanczakDominik** [joglekara/VlaPy#25]
#23 helped a ton for rendering the docstrings. However, going through them, now, I found https://vlapy.readthedocs.io/en/latest/code/fokker-planck.html#vlapy.core.lenard_bernstein.make_philharmonic_matrix and completely stumbled on `vax`. It would be immensely helpful for new users to add even a few words for each argument, leaving no function undocumented. Since the arguments are often the same between multiple functions, the actual workload probably won't be that high.

[Type hints are also always a great idea!](https://docs.python.org/3/library/typing.html)

Also, I'm sorry for doing this review in this kind of staggered manner. I hope you don't mind!

**Comment by joglekara** [comment]
Check out the linked PR when you have a chance.

No problem with the review style at all. I think I almost prefer it this way. 

As to type hints, I'm interested! Maybe that's another collaboration opportunity for us?
