### ISSUE TITLE
Better describe the goal, target audience of the project

### ISSUE THREAD

**Issue by StanczakDominik** [joglekara/VlaPy#31]
Hey, I'm getting back to reviewing the project (sorry for the delay!). I got to this point:

>  A statement of need: Do the authors clearly state what problems the software is designed to solve and who the target audience is?

And in the documentation and README I can see only

> VlaPy is a 1-spatial-dimension, 1-velocity-dimension, Vlasov-Poisson-Fokker-Planck code written in Python. The Vlasov-Poisson-Fokker-Planck system of equations is commonly used in plasma physics.

I think this could be expanded a little. The goal is stated pretty clearly, but the target audience is not mentioned, except very broadly (plasma physicists).

**Comment by joglekara** [comment]
Thanks for the feedback. Will expand on that a bit more.

**Comment by StanczakDominik** [comment]
I just got to the actual paper, and the section in there sounds good :)

**Comment by joglekara** [comment]
Ah, thanks!

In that case, should we close this? 

Or do you believe I should add that to the README as well? It doesn't seem like most repositories do that but I'm happy to be proven wrong!

**Comment by StanczakDominik** [comment]
I think it'd make sense for it to be in the readme as well. That's the first place someone stumbling upon a project looks at.

**Comment by joglekara** [comment]
Okay, sounds good. Take a look at #34
