### ISSUE TITLE
Anomalous dynamics for very small collision frequencies

### ISSUE THREAD

**Issue by joglekara** [joglekara/VlaPy#46]
By very small, I mean `nu_ee < 10^{-6}`. Needs more description here but e.g. 
![image](https://user-images.githubusercontent.com/13438206/88069376-3bc23300-cb26-11ea-969f-35b3e2c46a79.png)

**Comment by StanczakDominik** [comment]
Looks like floating point errors, no? Stepping through the code with a debugger and seeing when the numbers become less than machine epsilon would probably help pin this down. 

I'm not entirely sure there's anything that can be done except transitioning to a normalized system of units though :( (can't remember if one is used here)

**Comment by joglekara** [comment]
Yeah, likely related, if not exactly that. This is happening when `nu < 1e-6` so I think it's something to do with the implicit solver + small collision frequency + small numbers in the tail of the distribution. The system is already normalized to thermal units so i'm not sure if there's anywhere else to go there! We could try to increase the precision if need be.

Either way, just thought I'd report it here for posterity's sake! I will also post a full bug report with the settings I used for that run when I get a chance.
