### ISSUE TITLE
Missing figure in README

### ISSUE THREAD

**Issue by dpsanders** [joglekara/VlaPy#79]
The README says "This page will look like the following", but no figure is shown.

**Comment by joglekara** [comment]
@dpsanders , can you confirm which branch you saw this on? There's a chance you found it on the `paper` branch which doesn't have the most recent `README`. 

Can you please check the `README` on `master`? I've merged in the changes from `paper` on to `master` already.

**Comment by dpsanders** [comment]
It's fixed now, thanks!
