### ISSUE TITLE
Missing dependency?

### ISSUE THREAD

**Issue by dpsanders** [joglekara/VlaPy#80]
I ran the installation instructions but got

```
dpsanders$ python3 run_vlapy.py
Traceback (most recent call last):
  File "run_vlapy.py", line 30, in <module>
    from diagnostics import landau_damping, z_function
ModuleNotFoundError: No module named 'diagnostics'
```

**Comment by dpsanders** [comment]
By the way there seem to be a huge number of dependencies for what is supposed to be a simple simulation code. 

I'm guessing this is due to `mlflow`. Perhaps that piece should be separated out and made optional somehow?

**Comment by joglekara** [comment]
Ah sorry, I just hadn't updated `run_vlapy.py` after a recent refactor where the diagnostics were promoted into the main codebase.

You're right about the dependencies coming from mlflow. As you can see, the `setup.py` is actually quite lightweight. I think having a built-in simulation manager does wonders for workflow. It's also a very good Open Source project now supported by the linux-foundation.

**Comment by dpsanders** [comment]
The new version runs perfectly, thanks!
