### ISSUE TITLE
TypeError: start_run() missing 1 required positional argument: 'uris'

### ISSUE THREAD

**Issue by TomGoffrey** [joglekara/VlaPy#81]
Running `$ python3 run_vlapy.py` on commit b66c6748 I obtain the following error:

```
Traceback (most recent call last):
  File "run_vlapy.py", line 84, in <module>
    name=mlflow_exp_name,
TypeError: start_run() missing 1 required positional argument: 'uris'
```

Looking at `run_vlapy.py` and `vlapy/manager.py` it does appear that there's a missing argument.

**Comment by joglekara** [comment]
Ah yes. I added the `URI` for the mlflow-server as a flag. This lets you connect to any mlflow server you may have staged on the web. PR submitted and am currently waiting on tests
