### ISSUE TITLE
invalide experiment id

### ISSUE THREAD

**Issue by subodhdahal1988** [joglekara/VlaPy#98]
trying to run run_nlepw.py or any other code  throw this error

.......................................................................

File "/Volumes/subodh/MS/plasma/landau/.venv/lib/python3.11/site-packages/mlflow/tracking/fluent.py", line 294, in start_run
    _validate_experiment_id_type(experiment_id)
  File "/Volumes/subodh/MS/plasma/landau/.venv/lib/python3.11/site-packages/mlflow/utils/validation.py", line 359, in _validate_experiment_id_type
    raise MlflowException(
mlflow.exceptions.MlflowException: Invalid experiment id: <Experiment: artifact_location='file:///Volumes/subodh/MS/plasma/landau/VlaPy-master/mlruns/259967108510978607', creation_time=1700213405953, experiment_id='259967108510978607', last_update_time=1700213405953, lifecycle_stage='active', name='landau-damping', tags={}> of type <class 'mlflow.entities.experiment.Experiment'>. Must be one of str, int, or None.

.......................................................................

**Comment by joglekara** [comment]
thanks for writing up an issue. it should be fixed now
